# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_type', models.CharField(choices=[('GA', 'Gatekeeper'), ('IN', 'Insight'), ('MA', 'Masterpiece'), ('FI', 'Finder'), ('WO', 'Workbench')], max_length=2)),
            ],
        ),
    ]
