# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hurdle_period', models.PositiveIntegerField(default=0)),
                ('hurdle', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.PositiveIntegerField(default=0)),
                ('discount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_customer_success', models.BooleanField(default=False)),
                ('renewable_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('non_renewable_income', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=3)),
                ('start_date', models.DateTimeField()),
                ('renewal_date', models.DateTimeField()),
                ('termination_clause', models.CharField(choices=[('OM', 'One Month'), ('OQ', 'One Quarter'), ('OY', 'One Year')], max_length=2)),
                ('term', models.DurationField()),
                ('plants', models.PositiveIntegerField()),
                ('catalogues', models.PositiveIntegerField()),
                ('banding', models.PositiveIntegerField()),
                ('languages', models.CharField(choices=[('EN', 'English'), ('AM', 'American'), ('SP', 'Spanish'), ('PO', 'Portugese'), ('CH', 'Chinese')], max_length=2)),
                ('is_active', models.BooleanField(default=False)),
                ('account_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.AccountManager')),
                ('account_manager_commission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_manager_commission', to='contracts.Commission')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('executive_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_contact', to='contracts.Contact')),
                ('key_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_user', to='contracts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Partner'),
        ),
        migrations.AddField(
            model_name='contract',
            name='partner_commission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_commission', to='contracts.Commission'),
        ),
        migrations.AddField(
            model_name='contract',
            name='project_sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_sponsor', to='contracts.Contact'),
        ),
        migrations.AddField(
            model_name='accountmanager',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.Contact'),
        ),
    ]
