# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20170309_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseanimal',
            name='name',
            field=models.CharField(default='Holy-paper', max_length=50),
        ),
        migrations.AlterField(
            model_name='cage',
            name='name',
            field=models.CharField(default='Dawn-brook', max_length=50),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='name',
            field=models.CharField(default='Wild-sunset', max_length=50),
        ),
    ]
