# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-09 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_auto_20170309_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseanimal',
            name='name',
            field=models.CharField(default='Cool-cloud', max_length=50),
        ),
        migrations.AlterField(
            model_name='cage',
            name='name',
            field=models.CharField(default='Falling-pine', max_length=50),
        ),
        migrations.AlterField(
            model_name='cage',
            name='zoo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to='zoo.Zoo'),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='name',
            field=models.CharField(default='Lingering-sea', max_length=50),
        ),
    ]
