# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0005_auto_20170309_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseanimal',
            name='name',
            field=models.CharField(default='Crimson-field', max_length=50),
        ),
        migrations.AlterField(
            model_name='cage',
            name='name',
            field=models.CharField(default='Falling-wave', max_length=50),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='name',
            field=models.CharField(default='Patient-fog', max_length=50),
        ),
    ]
