# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-28 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_auto_20170327_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseanimal',
            name='name',
            field=models.CharField(default=b'Wandering-frost', max_length=50),
        ),
        migrations.AlterField(
            model_name='cage',
            name='name',
            field=models.CharField(default=b'Spring-field', max_length=50),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='name',
            field=models.CharField(default=b'Twilight-dawn', max_length=50),
        ),
    ]
