# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('gatekeeper_integration', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('LE', 'Lead'), ('OB', 'Onboarding'), ('KO', 'Kick-off'), ('GL', 'Go Live'), ('SU', 'Support'), ('BU', 'Business as Usual')], max_length=2)),
                ('consultant', models.CharField(choices=[('PH', 'Peter Hardy'), ('PS', 'Paul Shoesmith')], max_length=2)),
                ('project_manager', models.CharField(choices=[('ES', 'Esther Saez'), ('IG', 'Isabel Giraldo'), ('JM', 'Jonathan Melunsky'), ('MR', 'Matthew Rees'), ('OE', 'Olola Elias')], max_length=2)),
                ('on_sell', models.BooleanField(default=False)),
                ('initial_start_date', models.DateTimeField()),
                ('product', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
